# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'drugie.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormMainWindow(object):
    def setupUi(self, FormMainWindow):
        FormMainWindow.setObjectName("FormMainWindow")
        FormMainWindow.resize(400, 300)
        self.label = QtWidgets.QLabel(FormMainWindow)
        self.label.setGeometry(QtCore.QRect(150, 110, 131, 71))
        self.label.setObjectName("label")

        self.retranslateUi(FormMainWindow)
        QtCore.QMetaObject.connectSlotsByName(FormMainWindow)

    def retranslateUi(self, FormMainWindow):
        _translate = QtCore.QCoreApplication.translate
        FormMainWindow.setWindowTitle(_translate("FormMainWindow", "Main"))
        self.label.setText(_translate("FormMainWindow", "Drugie okno"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormMainWindow = QtWidgets.QWidget()
    ui = Ui_FormMainWindow()
    ui.setupUi(FormMainWindow)
    FormMainWindow.show()
    sys.exit(app.exec_())
